# Generated by Django 4.2.4 on 2023-09-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('lunch_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationInvites',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.organization')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(max_length=100)),
                ('TTL', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to='profile_image/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('password_hash', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('bank_number', models.CharField(max_length=20)),
                ('bank_code', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=30)),
                ('bank_region', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isAdmin', models.BooleanField(default=False)),
                ('lunch_credit_balance', models.IntegerField()),
                ('currency', models.CharField(max_length=255)),
                ('currency_code', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField()),
                ('org_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationLunchWallet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
            ],
        ),
    ]
