# Generated by Django 4.2.5 on 2023-09-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
