# Generated by Django 4.2.5 on 2023-09-21 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvites',
            name='TTL',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 12, 34, 23, 896924, tzinfo=datetime.timezone.utc)),
        ),
    ]
