# Generated by Django 4.2.5 on 2023-09-21 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_organizationinvites_ttl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvites',
            name='TTL',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 13, 51, 21, 861959, tzinfo=datetime.timezone.utc)),
        ),
    ]
